# Generated by Django 4.1.4 on 2023-01-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=128)),
                ('niveau', models.CharField(max_length=128)),
                ('discription', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=128)),
                ('mode', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=128)),
                ('prix', models.CharField(max_length=128)),
                ('lieu', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'annonce',
            },
        ),
    ]
