# Generated by Django 4.1.4 on 2023-01-30 08:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_annonce1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_path),
        ),
    ]
