# Generated by Django 4.1.4 on 2023-01-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_annonce1_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce1',
            old_name='image',
            new_name='image1',
        ),
    ]
