# Generated by Django 4.1.4 on 2023-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_annonce1_annoncee'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoncee',
            name='img',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
