# Generated by Django 4.1.4 on 2023-02-07 20:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_annoncee_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=128)),
                ('niveau', models.CharField(max_length=128)),
                ('discription', models.CharField(max_length=128)),
                ('mode', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=128)),
                ('prix', models.CharField(max_length=128)),
                ('lieu', models.CharField(max_length=128)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=core.models.upload_path)),
                ('img', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'favoris',
            },
        ),
    ]
