# Generated by Django 4.1.4 on 2023-02-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favoris'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favoris',
        ),
    ]
