# Generated by Django 4.1.4 on 2023-02-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_favoris'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoncee',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
