# Generated by Django 4.1.4 on 2023-02-08 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_annoncee_discription_alter_annoncee_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 2, 8, 23, 39, 33, 825801, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annoncee',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 2, 8, 23, 39, 56, 560273, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoris',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 2, 8, 23, 40, 0, 672405, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
